apiVersion: v1
kind: Pod
metadata:
  name: pterodactyl-wings
  labels:
    app: pterodactyl-wings
spec:
  hostNetwork: true
  initContainers:
    - name: init-config
      image: alpine
      command: ["sh", "-c", "cp /tmp/config/config.yml /etc/pterodactyl/"]
      volumeMounts:
        - name: config-secret
          mountPath: /tmp/config
        - name: pterodactyl-config
          mountPath: /etc/pterodactyl
  containers:
    - name: wings
      image: ghcr.io/pterodactyl/wings:latest
      ports:
        - containerPort: 8443
        - containerPort: 2022
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock
        - name: docker-containers
          mountPath: /var/lib/docker/containers/
        - name: pterodactyl-config
          mountPath: /etc/pterodactyl
        - name: pterodactyl-archives
          mountPath: /var/lib/pterodactyl/archives
        - name: pterodactyl-backups
          mountPath: /var/lib/pterodactyl/backups
        - name: pterodactyl-data
          mountPath: /var/lib/pterodactyl/volumes
          subPath: volumes
        - name: pterodactyl-data
          mountPath: /var/lib/pterodactyl/states.json
          subPath: states.json
        - name: pterodactyl-data
          mountPath: /var/lib/pterodactyl/wings.db
          subPath: wings.db
        - name: pterodactyl-logs
          mountPath: /var/log/pterodactyl/
        - name: pterodactyl-tmp
          mountPath: /tmp/pterodactyl/
        - name: tls-certs
          mountPath: /etc/certs/
          readOnly: true
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
    - name: docker-containers
      hostPath:
        path: /var/lib/docker/containers/
    - name: pterodactyl-config
      emptyDir: {}
    - name: config-secret
      secret:
        secretName: pterodactyl-wings-config
    - name: pterodactyl-archives
      persistentVolumeClaim:
        claimName: pterodactyl-archives-pvc
    - name: pterodactyl-backups
      persistentVolumeClaim:
        claimName: pterodactyl-backups-pvc
    - name: pterodactyl-data
      persistentVolumeClaim:
        claimName: pterodactyl-data-pvc
    - name: pterodactyl-logs
      emptyDir: {}
    - name: pterodactyl-tmp
      emptyDir: {}
    - name: tls-certs
      secret:
        secretName: pterodactyl-wings-tls
